"""The world: a believable frontier company seeded into SQLite — and now an
edge-case-rich one, so a tool that walks it meets the data a *real* dump hits.

Deadwood Telegraph & Trust Co. — a bank and telegraph office. Employees, customers,
accounts, transactions, internal telegrams, an audit log, API keys and live staff
sessions, all generated by a small seeded faker (stdlib only) so the data looks
real and is the same every time. The company's older paper sits in a second,
ATTACHed ledger (`archive`) — a separate database on the same connection.

What makes it a realistic *target* — and exactly where a tool's edge-case bugs
surface when it walks the data out:

  * **NULL cells in dumpable tables.** A dump concatenates each row; one NULL cell
    makes the whole row NULL, and `group_concat` skips NULLs — so that row silently
    vanishes. A tool that doesn't coalesce loses rows and never notices.
  * **`group_concat` modelled like MySQL** (see `_GroupConcat`): NULLs skipped and
    the result capped at `group_concat_max_len` (1024 bytes). A table bigger than
    that truncates mid-dump, with no error — a whole-table read loses the tail.
  * **values longer than 32 chars, tables over 1024 bytes** — to exercise chunked /
    error-window extraction (extractvalue truncates ~32 chars per read).
  * **unicode / non-ASCII values** — to exercise an ASCII-first extractor's fallback.
  * **a second ATTACHed database** — cross-database enumeration.

Levels read from this shared world and seed their own secrets on top.
"""

from __future__ import annotations

import hashlib
import random
import sqlite3
import time as _time

# Name pools — a deliberate mix of ASCII and accented/non-ASCII, so dumped data
# carries unicode an ASCII-first extractor has to fall back for.
_FIRST = [
    "Wyatt", "Martha", "Calamity", "Seth", "Al", "Sol", "Jane", "Charlie", "Doc",
    "Ellis", "Nora", "Sage", "Hattie", "Cyrus", "Mabel", "Otis", "Pearl", "Gus",
    "Ada", "Levi", "Ruth", "Silas", "Della", "Amos", "Iris", "Roy", "Etta", "Hank",
    "Cora", "Jeb", "Lula", "Virgil", "Tess", "Boone", "Winnie", "Clay", "Goldie",
    "José", "Désirée", "Søren", "Ingrid", "Lóránt", "Zoë", "Anaïs", "Mateus",
]
_LAST = [
    "Earp", "Bullock", "Hickok", "Canary", "Swearengen", "Star", "Utter", "Holliday",
    "Tilghman", "Masterson", "Garrett", "Cody", "Oakley", "Ringo", "Younger", "Dalton",
    "Plummer", "Slade", "Boot", "Hardin", "Doolin", "Starr", "Bass", "Reeves",
    "Muñoz", "Lefèvre", "Bjørn", "O'Hara", "Çelik",
]
_TOWNS = [
    "Deadwood", "Tombstone", "Dodge City", "Abilene", "Cheyenne", "Laramie", "Yuma",
    "Silverton", "Leadville", "Virginia City", "Bisbee", "Tascosa", "Cañon City", "El Paso",
]
_ROLES = [
    "Teller", "Head Teller", "Clerk", "Telegraph Operator", "Bookkeeper", "Vault Manager",
    "Loan Officer", "Branch Manager", "Stagecoach Agent", "Auditor",
]
_MEMOS = [
    "deposit, gold dust", "withdrawal, cash", "wire transfer", "loan repayment",
    "stagecoach freight", "saloon takings", "claim payout", "cattle sale",
    "telegraph fee", "vault audit adjustment",
]
_DOMAIN = "deadwood-trust.example"

# Weak, crackable passwords on purpose — md5'd in the DB, so a dump leaks a hash a
# wordlist breaks (the first step of the heist chain: creds -> login -> the vault).
_PASSWORDS = ["summer76", "letmein", "goldrush", "deadwood", "trotter",
              "marshal", "blackhills", "aceshigh", "wagon", "telegraph"]


def _slugify(name: str) -> str:
    # Keep it ASCII-ish for usernames/emails, but don't strip the data of unicode —
    # the display name (and notes, towns) keep their accents.
    return "".join(ch for ch in name.lower() if ch.isalnum())


def _sleep(n):
    """A SQLite `sleep()` — real engines have one natively; SQLite doesn't, so the
    time-based levels need it provided. Capped, so an injection can't hang the range."""
    try:
        _time.sleep(min(float(n), 5))
    except (TypeError, ValueError):
        pass
    return 0


class _GroupConcat:
    """`group_concat` modelled on MySQL, so a SQLite-backed range reproduces the two
    bugs a real whole-table dump hits:

      1. **NULLs are skipped.** A tool builds each row as `c0 || sep || c1 || …`; one
         NULL cell makes that expression NULL, and a NULL is dropped from the
         aggregate — so the entire row disappears from the dump.
      2. **The result is capped at `group_concat_max_len` bytes** (MySQL's default
         1024). A table whose concatenated form is larger comes back truncated, with
         no error — the tail of the table is simply missing.

    Variadic, to accept both `group_concat(x)` and `group_concat(x, sep)` (the 2-arg
    SQLite form hickok emits). Registered in `build()`, replacing SQLite's built-in
    for every connection in the range."""

    MAX_LEN = 1024            # group_concat_max_len, in bytes

    def __init__(self):
        self._parts: list[str] = []
        self._sep = ","

    def step(self, *args):
        if not args or args[0] is None:
            return                                    # MySQL skips NULL values
        if len(args) > 1 and args[1] is not None:
            self._sep = str(args[1])
        self._parts.append(str(args[0]))

    def finalize(self):
        if not self._parts:
            return None
        out = self._sep.join(self._parts)
        raw = out.encode("utf-8")
        if len(raw) > self.MAX_LEN:                   # truncate by bytes, like MySQL
            out = raw[: self.MAX_LEN].decode("utf-8", "ignore")
        return out


def _concat(*args):
    """MySQL `concat`: NULL if any argument is NULL (otherwise the joined text).
    Provided so the range behaves like MySQL regardless of SQLite version, and so
    the NULL-drop bug shows on the concat() dump path too, not just `||`."""
    if any(a is None for a in args):
        return None
    return "".join(str(a) for a in args)


def _token(rng, n=40):
    """A long opaque token (> 32 chars) — API keys, session ids: realistic, and big
    enough to span more than one error-extraction window."""
    return "".join(rng.choice("0123456789abcdef") for _ in range(n))


def build(db: sqlite3.Connection, seed: int = 1876) -> None:
    """(Re)build the company world into `db`. Deterministic for a given seed."""
    db.create_function("sleep", 1, _sleep)
    db.create_aggregate("group_concat", -1, _GroupConcat)   # MySQL-modelled (see class)
    db.create_function("concat", -1, _concat)               # MySQL concat: NULL if any arg is NULL
    rng = random.Random(seed)

    # The older paper: a second database on the same connection (cross-db surface).
    if _attached(db, "archive"):                 # so a rebuild on one connection re-attaches cleanly
        db.execute("DETACH DATABASE archive")
    db.execute("ATTACH DATABASE ':memory:' AS archive")

    db.executescript("""
        DROP TABLE IF EXISTS employees;
        DROP TABLE IF EXISTS customers;
        DROP TABLE IF EXISTS accounts;
        DROP TABLE IF EXISTS transactions;
        DROP TABLE IF EXISTS telegrams;
        DROP TABLE IF EXISTS audit_log;
        DROP TABLE IF EXISTS api_keys;
        DROP TABLE IF EXISTS sessions;
        DROP TABLE IF EXISTS secrets;
        CREATE TABLE employees (id INTEGER PRIMARY KEY, name TEXT, role TEXT, town TEXT,
                                username TEXT, pw_md5 TEXT, email TEXT,
                                ssn TEXT, mfa_secret TEXT, api_token TEXT);
        CREATE TABLE customers (id INTEGER PRIMARY KEY, name TEXT, town TEXT, email TEXT,
                                phone TEXT, joined TEXT, notes TEXT);
        CREATE TABLE accounts (id INTEGER PRIMARY KEY, customer_id INTEGER, number TEXT,
                               kind TEXT, balance INTEGER, note TEXT);
        CREATE TABLE transactions (id INTEGER PRIMARY KEY, account_id INTEGER, day TEXT,
                                   amount INTEGER, memo TEXT);
        CREATE TABLE telegrams (id INTEGER PRIMARY KEY, sender TEXT, recipient TEXT,
                                subject TEXT, body TEXT);
        CREATE TABLE audit_log (id INTEGER PRIMARY KEY, ts TEXT, actor TEXT, action TEXT, detail TEXT);
        CREATE TABLE api_keys (id INTEGER PRIMARY KEY, owner TEXT, scope TEXT, token TEXT, revoked INTEGER);
        CREATE TABLE sessions (id INTEGER PRIMARY KEY, username TEXT, token TEXT, role TEXT, created TEXT);
        CREATE TABLE secrets (id INTEGER PRIMARY KEY, label TEXT, value TEXT);

        CREATE TABLE archive.ledger_1875 (id INTEGER PRIMARY KEY, day TEXT, entry TEXT, amount INTEGER);
        CREATE TABLE archive.secrets (id INTEGER PRIMARY KEY, label TEXT, value TEXT);
    """)

    def person():
        return f"{rng.choice(_FIRST)} {rng.choice(_LAST)}"

    # employees — weak md5 passwords (crackable), some with NULL mfa_secret (a NULL
    # cell that drops the whole row from a naive group_concat dump), all with a long
    # api_token (> 32 chars, pushes the table over 1024 bytes for the cap to bite).
    employees, used = [], set()
    for i in range(1, 19):
        name = person()
        user = _slugify(name)
        while user in used or not user:
            name = person()
            user = _slugify(name)
        used.add(user)
        pw = rng.choice(_PASSWORDS)
        mfa = None if rng.random() < 0.4 else _token(rng, 16)     # ~40% NULL — rows that vanish
        employees.append((i, name, rng.choice(_ROLES), rng.choice(_TOWNS), user,
                          hashlib.md5(pw.encode()).hexdigest(), f"{user}@{_DOMAIN}",
                          f"{rng.randint(100, 699):03d}-{rng.randint(10, 99)}-{rng.randint(1000, 9999)}",
                          mfa, _token(rng, 40)))
    db.executemany("INSERT INTO employees VALUES (?,?,?,?,?,?,?,?,?,?)", employees)

    # customers + accounts + a ledger of transactions. NULL email/phone on some
    # (more vanishing rows), and a notes field that carries unicode and long text.
    _NOTES = [
        "Prefers the Cheyenne branch; señora paid in gold dust — café receipts on file.",
        "Disputed a wire to El Paso; resolved Fríday. Note the accented name on record.",
        "VIP — Désirée's account, do not freeze without the Branch Manager's sign-off.",
        None, None,
        "Stagecoach freight settled monthly; façade repairs billed to the saloon account.",
    ]
    acc_id = tx_id = 0
    for cid in range(1, 41):
        name = person()
        town = rng.choice(_TOWNS)
        email = None if rng.random() < 0.3 else f"{_slugify(name)}@mail.example"
        phone = None if rng.random() < 0.5 else f"307-{rng.randint(200, 899)}-{rng.randint(1000, 9999)}"
        db.execute("INSERT INTO customers VALUES (?,?,?,?,?,?,?)",
                   (cid, name, town, email, phone,
                    f"187{rng.randint(2, 9)}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}",
                    rng.choice(_NOTES)))
        for _ in range(rng.randint(1, 2)):
            acc_id += 1
            kind = rng.choice(["checking", "savings", "gold deposit"])
            bal = rng.randint(20, 9000) * (100 if kind == "gold deposit" else 1)
            note = None if rng.random() < 0.6 else rng.choice(
                ["dormant since '74", "co-signed", "overdraft waiver on file", "flagged for audit"])
            db.execute("INSERT INTO accounts VALUES (?,?,?,?,?,?)",
                       (acc_id, cid, f"DW-{rng.randint(10000, 99999)}", kind, bal, note))
            for _ in range(rng.randint(2, 6)):
                tx_id += 1
                db.execute("INSERT INTO transactions VALUES (?,?,?,?,?)",
                           (tx_id, acc_id, f"187{rng.randint(2, 9)}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}",
                            rng.randint(-2000, 5000), rng.choice(_MEMOS)))

    # internal telegrams — long bodies (> 32 chars), a couple in unicode.
    _SUBJECTS = ["VAULT COMBINATION CHANGED", "SHIPMENT DELAYED", "AUDIT NEXT WEEK",
                 "NEW TELLER STARTS MONDAY", "WIRE CONFIRMED", "CLOSE EARLY FRIDAY"]
    for i in range(1, 13):
        body = ("STOP. " + rng.choice(_MEMOS).upper() + ". CONFIRM RECEIPT BY RETURN WIRE "
                "AND LOG TO THE LEDGER. STOP. " + ("RÉSUMÉ DEL ENVÍO MAÑANA. STOP." if i % 5 == 0 else ""))
        db.execute("INSERT INTO telegrams VALUES (?,?,?,?,?)",
                   (i, person(), person(), rng.choice(_SUBJECTS), body))

    # a big audit log — long detail lines, easily over the 1024-byte group_concat cap
    # so a whole-table dump truncates; the tail of the table is what a tool then loses.
    _ACTIONS = ["LOGIN", "WIRE", "VAULT_OPEN", "OVERRIDE", "EXPORT", "PASSWORD_RESET", "AUDIT"]
    for i in range(1, 61):
        actor = rng.choice(employees)[4]
        detail = (f"{rng.choice(_ACTIONS).lower()} by {actor} from terminal "
                  f"{rng.randint(1, 9)} — ref #{_token(rng, 12)}; amount ${rng.randint(5, 90000)}; "
                  f"branch {rng.choice(_TOWNS)}; note: {rng.choice(_MEMOS)}")
        db.execute("INSERT INTO audit_log VALUES (?,?,?,?,?)",
                   (i, f"1876-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}T{rng.randint(8, 18):02d}:{rng.randint(0, 59):02d}",
                    actor, rng.choice(_ACTIONS), detail))

    # API keys and live staff sessions — long opaque tokens (> 32 chars). Dumping
    # the sessions table is the pivot of the heist (a live token -> ride the cookie).
    for i, emp in enumerate(employees[:10], 1):
        db.execute("INSERT INTO api_keys VALUES (?,?,?,?,?)",
                   (i, emp[4], rng.choice(["read", "read-write", "admin"]), "dwk_" + _token(rng, 48),
                    1 if rng.random() < 0.2 else 0))
    for i, emp in enumerate(employees[:12], 1):
        db.execute("INSERT INTO sessions VALUES (?,?,?,?,?)",
                   (i, emp[4], _token(rng, 48), "teller",
                    f"1876-06-{rng.randint(1, 28):02d}T{rng.randint(8, 18):02d}:00"))

    # company-wide secrets (shared baseline; levels add their own flag on top). One
    # carries unicode, a couple are long — value channels and blind walks meet both.
    db.executemany("INSERT INTO secrets (label, value) VALUES (?,?)", [
        ("smtp_relay", "telegraph:hunter2@relay.deadwood-trust.example"),
        ("backup_passphrase", "wagons-roll-at-dawn-then-regroup-at-the-gulch-1876"),
        ("telegraph_cipher_key", "clé-de-télégraphe-☠-1876-déjà-vu"),
    ])

    # the archive (cross-db): old ledger + an archived secret only reachable by
    # qualifying the other database.
    for i in range(1, 21):
        db.execute("INSERT INTO archive.ledger_1875 VALUES (?,?,?,?)",
                   (i, f"1875-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}",
                    rng.choice(_MEMOS) + " — carried forward from the old book", rng.randint(-1500, 4000)))
    db.execute("INSERT INTO archive.secrets (label, value) VALUES (?,?)",
               ("archived_vault_combo", "left-7-right-31-left-19 (sealed 1875, never rotated)"))

    db.commit()


def _attached(db: sqlite3.Connection, name: str) -> bool:
    """Whether a database `name` is already attached (so a rebuild can re-attach)."""
    return any(r[1] == name for r in db.execute("PRAGMA database_list"))
