"""The world: a believable frontier company seeded into SQLite.

Deadwood Telegraph & Trust Co. — a bank and telegraph office. Employees, customers,
accounts, transactions and internal telegrams, all generated by a small seeded
faker (stdlib only) so the data looks real and is the same every time. Levels read
from this shared world and seed their own secrets on top.
"""

from __future__ import annotations

import hashlib
import random
import sqlite3
import time as _time

_FIRST = [
    "Wyatt", "Martha", "Calamity", "Seth", "Al", "Sol", "Jane", "Charlie", "Doc",
    "Ellis", "Nora", "Sage", "Hattie", "Cyrus", "Mabel", "Otis", "Pearl", "Gus",
    "Ada", "Levi", "Ruth", "Silas", "Della", "Amos", "Iris", "Roy", "Etta", "Hank",
    "Cora", "Jeb", "Lula", "Virgil", "Tess", "Boone", "Winnie", "Clay", "Goldie",
]
_LAST = [
    "Earp", "Bullock", "Hickok", "Canary", "Swearengen", "Star", "Utter", "Holliday",
    "Tilghman", "Masterson", "Garrett", "Cody", "Oakley", "Ringo", "Younger", "Dalton",
    "Plummer", "Slade", "Boot", "Hardin", "Doolin", "Starr", "Bass", "Reeves",
]
_TOWNS = [
    "Deadwood", "Tombstone", "Dodge City", "Abilene", "Cheyenne", "Laramie", "Yuma",
    "Silverton", "Leadville", "Virginia City", "Bisbee", "Tascosa",
]
_ROLES = [
    "Teller", "Head Teller", "Clerk", "Telegraph Operator", "Bookkeeper", "Vault Manager",
    "Loan Officer", "Branch Manager", "Stagecoach Agent", "Auditor",
]
_MEMOS = [
    "deposit, gold dust", "withdrawal, cash", "wire transfer", "loan repayment",
    "stagecoach freight", "saloon takings", "claim payout", "cattle sale",
    "telegraph fee", "vault audit adjustment",
]
_DOMAIN = "deadwood-trust.example"


def _slugify(name: str) -> str:
    return name.lower().replace(" ", "")


def _sleep(n):
    """A SQLite `sleep()` — real engines have one natively; SQLite doesn't, so the
    time-based level (The Telegraph) needs it provided. Capped, so an injection
    can't hang the range."""
    try:
        _time.sleep(min(float(n), 5))
    except (TypeError, ValueError):
        pass
    return 0


def build(db: sqlite3.Connection, seed: int = 1876) -> None:
    """(Re)build the company world into `db`. Deterministic for a given seed."""
    db.create_function("sleep", 1, _sleep)
    rng = random.Random(seed)
    db.executescript("""
        DROP TABLE IF EXISTS employees;
        DROP TABLE IF EXISTS customers;
        DROP TABLE IF EXISTS accounts;
        DROP TABLE IF EXISTS transactions;
        DROP TABLE IF EXISTS telegrams;
        DROP TABLE IF EXISTS secrets;
        CREATE TABLE employees (id INTEGER PRIMARY KEY, name TEXT, role TEXT, town TEXT,
                                username TEXT, pw_md5 TEXT, email TEXT);
        CREATE TABLE customers (id INTEGER PRIMARY KEY, name TEXT, town TEXT, email TEXT, joined TEXT);
        CREATE TABLE accounts (id INTEGER PRIMARY KEY, customer_id INTEGER, number TEXT,
                               kind TEXT, balance INTEGER);
        CREATE TABLE transactions (id INTEGER PRIMARY KEY, account_id INTEGER, day TEXT,
                                   amount INTEGER, memo TEXT);
        CREATE TABLE telegrams (id INTEGER PRIMARY KEY, sender TEXT, recipient TEXT,
                                subject TEXT, body TEXT);
        CREATE TABLE secrets (id INTEGER PRIMARY KEY, label TEXT, value TEXT);
    """)

    def person():
        return f"{rng.choice(_FIRST)} {rng.choice(_LAST)}"

    # employees — note the weak MD5 password hashes (a lesson for later levels)
    employees = []
    used = set()
    for i in range(1, 19):
        name = person()
        user = _slugify(name)
        while user in used:
            name = person()
            user = _slugify(name)
        used.add(user)
        pw = rng.choice(["summer76", "letmein", "goldrush", "deadwood", "trotter",
                         "marshal", "blackhills", "aceshigh", "wagon", "telegraph"])
        employees.append((i, name, rng.choice(_ROLES), rng.choice(_TOWNS), user,
                          hashlib.md5(pw.encode()).hexdigest(), f"{user}@{_DOMAIN}"))
    db.executemany("INSERT INTO employees VALUES (?,?,?,?,?,?,?)", employees)

    # customers + their accounts + a ledger of transactions
    acc_id = tx_id = 0
    for cid in range(1, 41):
        name = person()
        town = rng.choice(_TOWNS)
        db.execute("INSERT INTO customers VALUES (?,?,?,?,?)",
                   (cid, name, town, f"{_slugify(name)}@mail.example",
                    f"187{rng.randint(2, 9)}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}"))
        for _ in range(rng.randint(1, 2)):
            acc_id += 1
            kind = rng.choice(["checking", "savings", "gold deposit"])
            bal = rng.randint(20, 9000) * (100 if kind == "gold deposit" else 1)
            db.execute("INSERT INTO accounts VALUES (?,?,?,?,?)",
                       (acc_id, cid, f"DW-{rng.randint(10000, 99999)}", kind, bal))
            for _ in range(rng.randint(2, 6)):
                tx_id += 1
                db.execute("INSERT INTO transactions VALUES (?,?,?,?,?)",
                           (tx_id, acc_id, f"187{rng.randint(2, 9)}-{rng.randint(1, 12):02d}-{rng.randint(1, 28):02d}",
                            rng.randint(-2000, 5000), rng.choice(_MEMOS)))

    # a few internal telegrams for colour (and a place to hide things)
    for i in range(1, 9):
        db.execute("INSERT INTO telegrams VALUES (?,?,?,?,?)",
                   (i, person(), person(), rng.choice(
                       ["VAULT COMBINATION CHANGED", "SHIPMENT DELAYED", "AUDIT NEXT WEEK",
                        "NEW TELLER STARTS MONDAY", "WIRE CONFIRMED", "CLOSE EARLY FRIDAY"]),
                    "STOP. " + rng.choice(_MEMOS).upper() + ". STOP."))
    db.commit()
